---
tasks:
  - name: Docker
    init: >
      ls -lrtha /home/gitpod/.ssh/ &&
      cd /tmp/ && git clone https://github.com/princerachit/pub.git
    command: >
      ls -lrtha /home/gitpod/.ssh/ &&
      cd /tmp/ && git clone https://github.com/princerachit/pub.git
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: true
