---
tasks:
  - name: Docker
    init: >
      echo ${MISC_SSH_PRIVATE_KEY} | base64 -d  > idkey && chmod 400 idkey &&
      GIT_SSH_COMMAND="ssh -i idkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git submodule update --init
    command: >
      echo "commssadnssd"
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: true
