---
tasks:
  - name: Docker
    init: >
      cd /tmp/ && git clone https://github.com/princerachit/pub.git && echo "init"
    command: >
      cd /tmp/ && git clone https://github.com/princerachit/pub.git echo "command"
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: true
