---
tasks:
  - name: Docker
    init: >
      ssh-keyscan github.com >> ~/.ssh/known_hosts &&
      git submodule update --init --quiet
    command: >
      echo "command"
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: true
