---
tasks:
  - name: Docker
    init: >
      echo "init"
    command: >
      echo "command"
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addComment: true
    addBadge: true
